-- 코드를 작성해주세요
SELECT YEAR(a.DIFFERENTIATION_DATE) as YEAR, (b.SIZE-a.SIZE_OF_COLONY) as YEAR_DEV, a.ID
FROM ECOLI_DATA AS a
LEFT JOIN (SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS SIZE
        FROM ECOLI_DATA
        GROUP BY YEAR(DIFFERENTIATION_DATE)) AS b
ON YEAR(a.DIFFERENTIATION_DATE) = b.YEAR
ORDER BY YEAR ASC, YEAR_DEV ASC